directory_finder = {
    # Images
    ".png": "Photos",
    ".jpg": "Photos",
    ".jpeg": "Photos",
    ".jfif": "Photos",
    ".webp": "Photos",
    ".gif": "Photos",
    ".bmp": "Photos",
    ".tiff": "Photos",
    ".tif": "Photos",
    ".svg": "Photos",
    ".ico": "Photos",
    ".heic": "Photos",
    ".heif": "Photos",
    ".raw": "Photos",
    ".psd": "Photos",
    ".ai": "Photos",
    ".eps": "Photos",
    ".xcf": "Photos",
    ".avif": "Photos",
    ".dng": "Photos",

    # Videos
    ".mp4": "Videos",
    ".mkv": "Videos",
    ".mov": "Videos",
    ".avi": "Videos",
    ".wmv": "Videos",
    ".flv": "Videos",
    ".webm": "Videos",
    ".mpeg": "Videos",
    ".mpg": "Videos",
    ".m4v": "Videos",
    ".3gp": "Videos",
    ".ts": "Videos",
    ".vob": "Videos",
    ".ogv": "Videos",

    # Audio
    ".mp3": "Audio",
    ".wav": "Audio",
    ".aac": "Audio",
    ".flac": "Audio",
    ".ogg": "Audio",
    ".wma": "Audio",
    ".m4a": "Audio",
    ".aiff": "Audio",
    ".aif": "Audio",
    ".opus": "Audio",
    ".mid": "Audio",
    ".midi": "Audio",
    ".amr": "Audio",
    ".ape": "Audio",

    # Documents
    ".pdf": "Documents",
    ".doc": "Documents",
    ".docx": "Documents",
    ".odt": "Documents",
    ".rtf": "Documents",
    ".txt": "Documents",
    ".tex": "Documents",
    ".wpd": "Documents",
    ".pages": "Documents",
    ".md": "Documents",
    ".rst": "Documents",

    # Spreadsheets
    ".xls": "Spreadsheets",
    ".xlsx": "Spreadsheets",
    ".xlsm": "Spreadsheets",
    ".xlsb": "Spreadsheets",
    ".csv": "Spreadsheets",
    ".tsv": "Spreadsheets",
    ".ods": "Spreadsheets",
    ".numbers": "Spreadsheets",

    # Presentations
    ".ppt": "Presentations",
    ".pptx": "Presentations",
    ".pptm": "Presentations",
    ".odp": "Presentations",
    ".key": "Presentations",

    # Programming and web development
    ".py": "Codes",
    ".pyw": "Codes",
    ".ipynb": "Codes",
    ".js": "Codes",
    ".jsx": "Codes",
    ".ts": "Codes",
    ".tsx": "Codes",
    ".html": "Codes",
    ".htm": "Codes",
    ".css": "Codes",
    ".scss": "Codes",
    ".sass": "Codes",
    ".less": "Codes",
    ".php": "Codes",
    ".java": "Codes",
    ".class": "Codes",
    ".jar": "Codes",
    ".c": "Codes",
    ".h": "Codes",
    ".cpp": "Codes",
    ".hpp": "Codes",
    ".cs": "Codes",
    ".vb": "Codes",
    ".go": "Codes",
    ".rs": "Codes",
    ".rb": "Codes",
    ".swift": "Codes",
    ".kt": "Codes",
    ".kts": "Codes",
    ".dart": "Codes",
    ".lua": "Codes",
    ".r": "Codes",
    ".m": "Codes",
    ".pl": "Codes",
    ".sh": "Codes",
    ".bash": "Codes",
    ".zsh": "Codes",
    ".ps1": "Codes",
    ".bat": "Codes",
    ".cmd": "Codes",
    ".sql": "Codes",
    ".xml": "Codes",
    ".xsl": "Codes",
    ".xslt": "Codes",
    ".json": "Codes",
    ".yaml": "Codes",
    ".yml": "Codes",
    ".toml": "Codes",
    ".ini": "Codes",
    ".env.example": "Codes",
    ".graphql": "Codes",
    ".gql": "Codes",
    ".vue": "Codes",
    ".svelte": "Codes",
    ".astro": "Codes",

    # Archives and compressed files
    ".zip": "Archives",
    ".rar": "Archives",
    ".7z": "Archives",
    ".tar": "Archives",
    ".gz": "Archives",
    ".bz2": "Archives",
    ".xz": "Archives",
    ".tgz": "Archives",
    ".zst": "Archives",
    ".lz": "Archives",
    ".lzma": "Archives",
    ".cab": "Archives",
    ".iso": "Archives",
    ".img": "Archives",
    ".dmg": "Archives",

    # Executables and installers
    ".exe": "Applications",
    ".msi": "Applications",
    ".msix": "Applications",
    ".appx": "Applications",
    ".appxbundle": "Applications",
    ".apk": "Applications",
    ".aab": "Applications",
    ".deb": "Applications",
    ".rpm": "Applications",
    ".appimage": "Applications",
    ".com": "Applications",

    # Fonts
    ".ttf": "Fonts",
    ".otf": "Fonts",
    ".woff": "Fonts",
    ".woff2": "Fonts",
    ".eot": "Fonts",

    # 3D models and design
    ".obj": "3D Models",
    ".stl": "3D Models",
    ".fbx": "3D Models",
    ".blend": "3D Models",
    ".gltf": "3D Models",
    ".glb": "3D Models",
    ".dae": "3D Models",
    ".3ds": "3D Models",
    ".step": "3D Models",
    ".stp": "3D Models",
    ".iges": "3D Models",
    ".igs": "3D Models",

    # Backup and database files
    ".bak": "Backups",
    ".backup": "Backups",
    ".old": "Backups",
    ".sqlite": "Databases",
    ".sqlite3": "Databases",
    ".db": "Databases",
    ".mdb": "Databases",
    ".accdb": "Databases",
    ".sqlitedb": "Databases",

    # Disk and system images
    ".vhd": "Disk Images",
    ".vhdx": "Disk Images",
    ".vmdk": "Disk Images",
    ".vdi": "Disk Images",
    ".qcow2": "Disk Images",

    # Certificates and keys
    ".pem": "Certificates",
    ".crt": "Certificates",
    ".cer": "Certificates",
    ".p12": "Certificates",
    ".pfx": "Certificates",
    ".pub": "Certificates",

    # Subtitles
    ".srt": "Subtitles",
    ".ass": "Subtitles",
    ".ssa": "Subtitles",
    ".vtt": "Subtitles",
    ".sub": "Subtitles",

    # E-books
    ".epub": "Ebooks",
    ".mobi": "Ebooks",
    ".azw": "Ebooks",
    ".azw3": "Ebooks",
    ".djvu": "Ebooks",

    # Game-related files
    ".pak": "Game Files",
    ".wad": "Game Files",
    ".unity3d": "Game Files",
    ".assetbundle": "Game Files",

    # Log and temporary files
    ".log": "Logs",
    ".tmp": "Temporary",
    ".temp": "Temporary",
    ".cache": "Temporary",

    # Data and machine learning
    ".parquet": "Data Files",
    ".feather": "Data Files",
    ".pkl": "Data Files",
    ".pickle": "Data Files",
    ".joblib": "Data Files",
    ".h5": "Data Files",
    ".hdf5": "Data Files",
    ".npy": "Data Files",
    ".npz": "Data Files",
    ".pt": "Data Files",
    ".pth": "Data Files",
    ".onnx": "Data Files",
    ".pb": "Data Files",

    # Configuration and dependency files
    ".lock": "Configuration",
    ".conf": "Configuration",
    ".config": "Configuration",
    ".properties": "Configuration",
    ".editorconfig": "Configuration",
    ".gitignore": "Configuration",
    ".gitattributes": "Configuration",
    ".dockerignore": "Configuration",
}